name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run local tests
        run: |
          forge test -vvv --no-match-contract "ForkTest"
        env:
          FOUNDRY_PROFILE: ci
        id: test-local

      - name: Run fork tests
        run: |
          forge test -vvv --match-contract "ForkTest"
        env:
          FOUNDRY_PROFILE: ci-fork
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          UNICHAIN_RPC_URL: ${{ secrets.UNICHAIN_RPC_URL }}
        id: test-fork
